# This is a basic workflow to help you get started with Actions

name: mirror

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: https://nicolasflamel.ensimag.fr/gl2023/gr5/gl21.git
          GIT_USERNAME: verninp
          GIT_PASSWORD: ${{ secrets.gitlab_password }}
